require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ScheduleItemsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # ScheduleItem. As you add validations to ScheduleItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ScheduleItemsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all schedule_items as @schedule_items" do
      schedule_item = ScheduleItem.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:schedule_items)).to eq([schedule_item])
    end
  end

  describe "GET show" do
    it "assigns the requested schedule_item as @schedule_item" do
      schedule_item = ScheduleItem.create! valid_attributes
      get :show, {:id => schedule_item.to_param}, valid_session
      expect(assigns(:schedule_item)).to eq(schedule_item)
    end
  end

  describe "GET new" do
    it "assigns a new schedule_item as @schedule_item" do
      get :new, {}, valid_session
      expect(assigns(:schedule_item)).to be_a_new(ScheduleItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested schedule_item as @schedule_item" do
      schedule_item = ScheduleItem.create! valid_attributes
      get :edit, {:id => schedule_item.to_param}, valid_session
      expect(assigns(:schedule_item)).to eq(schedule_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ScheduleItem" do
        expect {
          post :create, {:schedule_item => valid_attributes}, valid_session
        }.to change(ScheduleItem, :count).by(1)
      end

      it "assigns a newly created schedule_item as @schedule_item" do
        post :create, {:schedule_item => valid_attributes}, valid_session
        expect(assigns(:schedule_item)).to be_a(ScheduleItem)
        expect(assigns(:schedule_item)).to be_persisted
      end

      it "redirects to the created schedule_item" do
        post :create, {:schedule_item => valid_attributes}, valid_session
        expect(response).to redirect_to(ScheduleItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved schedule_item as @schedule_item" do
        post :create, {:schedule_item => invalid_attributes}, valid_session
        expect(assigns(:schedule_item)).to be_a_new(ScheduleItem)
      end

      it "re-renders the 'new' template" do
        post :create, {:schedule_item => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested schedule_item" do
        schedule_item = ScheduleItem.create! valid_attributes
        put :update, {:id => schedule_item.to_param, :schedule_item => new_attributes}, valid_session
        schedule_item.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested schedule_item as @schedule_item" do
        schedule_item = ScheduleItem.create! valid_attributes
        put :update, {:id => schedule_item.to_param, :schedule_item => valid_attributes}, valid_session
        expect(assigns(:schedule_item)).to eq(schedule_item)
      end

      it "redirects to the schedule_item" do
        schedule_item = ScheduleItem.create! valid_attributes
        put :update, {:id => schedule_item.to_param, :schedule_item => valid_attributes}, valid_session
        expect(response).to redirect_to(schedule_item)
      end
    end

    describe "with invalid params" do
      it "assigns the schedule_item as @schedule_item" do
        schedule_item = ScheduleItem.create! valid_attributes
        put :update, {:id => schedule_item.to_param, :schedule_item => invalid_attributes}, valid_session
        expect(assigns(:schedule_item)).to eq(schedule_item)
      end

      it "re-renders the 'edit' template" do
        schedule_item = ScheduleItem.create! valid_attributes
        put :update, {:id => schedule_item.to_param, :schedule_item => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested schedule_item" do
      schedule_item = ScheduleItem.create! valid_attributes
      expect {
        delete :destroy, {:id => schedule_item.to_param}, valid_session
      }.to change(ScheduleItem, :count).by(-1)
    end

    it "redirects to the schedule_items list" do
      schedule_item = ScheduleItem.create! valid_attributes
      delete :destroy, {:id => schedule_item.to_param}, valid_session
      expect(response).to redirect_to(schedule_items_url)
    end
  end

end
