require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe StudentGroupMarksController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # StudentGroupMark. As you add validations to StudentGroupMark, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StudentGroupMarksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all student_group_marks as @student_group_marks" do
      student_group_mark = StudentGroupMark.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:student_group_marks)).to eq([student_group_mark])
    end
  end

  describe "GET show" do
    it "assigns the requested student_group_mark as @student_group_mark" do
      student_group_mark = StudentGroupMark.create! valid_attributes
      get :show, {:id => student_group_mark.to_param}, valid_session
      expect(assigns(:student_group_mark)).to eq(student_group_mark)
    end
  end

  describe "GET new" do
    it "assigns a new student_group_mark as @student_group_mark" do
      get :new, {}, valid_session
      expect(assigns(:student_group_mark)).to be_a_new(StudentGroupMark)
    end
  end

  describe "GET edit" do
    it "assigns the requested student_group_mark as @student_group_mark" do
      student_group_mark = StudentGroupMark.create! valid_attributes
      get :edit, {:id => student_group_mark.to_param}, valid_session
      expect(assigns(:student_group_mark)).to eq(student_group_mark)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StudentGroupMark" do
        expect {
          post :create, {:student_group_mark => valid_attributes}, valid_session
        }.to change(StudentGroupMark, :count).by(1)
      end

      it "assigns a newly created student_group_mark as @student_group_mark" do
        post :create, {:student_group_mark => valid_attributes}, valid_session
        expect(assigns(:student_group_mark)).to be_a(StudentGroupMark)
        expect(assigns(:student_group_mark)).to be_persisted
      end

      it "redirects to the created student_group_mark" do
        post :create, {:student_group_mark => valid_attributes}, valid_session
        expect(response).to redirect_to(StudentGroupMark.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved student_group_mark as @student_group_mark" do
        post :create, {:student_group_mark => invalid_attributes}, valid_session
        expect(assigns(:student_group_mark)).to be_a_new(StudentGroupMark)
      end

      it "re-renders the 'new' template" do
        post :create, {:student_group_mark => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested student_group_mark" do
        student_group_mark = StudentGroupMark.create! valid_attributes
        put :update, {:id => student_group_mark.to_param, :student_group_mark => new_attributes}, valid_session
        student_group_mark.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested student_group_mark as @student_group_mark" do
        student_group_mark = StudentGroupMark.create! valid_attributes
        put :update, {:id => student_group_mark.to_param, :student_group_mark => valid_attributes}, valid_session
        expect(assigns(:student_group_mark)).to eq(student_group_mark)
      end

      it "redirects to the student_group_mark" do
        student_group_mark = StudentGroupMark.create! valid_attributes
        put :update, {:id => student_group_mark.to_param, :student_group_mark => valid_attributes}, valid_session
        expect(response).to redirect_to(student_group_mark)
      end
    end

    describe "with invalid params" do
      it "assigns the student_group_mark as @student_group_mark" do
        student_group_mark = StudentGroupMark.create! valid_attributes
        put :update, {:id => student_group_mark.to_param, :student_group_mark => invalid_attributes}, valid_session
        expect(assigns(:student_group_mark)).to eq(student_group_mark)
      end

      it "re-renders the 'edit' template" do
        student_group_mark = StudentGroupMark.create! valid_attributes
        put :update, {:id => student_group_mark.to_param, :student_group_mark => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested student_group_mark" do
      student_group_mark = StudentGroupMark.create! valid_attributes
      expect {
        delete :destroy, {:id => student_group_mark.to_param}, valid_session
      }.to change(StudentGroupMark, :count).by(-1)
    end

    it "redirects to the student_group_marks list" do
      student_group_mark = StudentGroupMark.create! valid_attributes
      delete :destroy, {:id => student_group_mark.to_param}, valid_session
      expect(response).to redirect_to(student_group_marks_url)
    end
  end

end
